title: "Handlers & Notifications"
summary: "Restart/reload services only when config changes."

example: |
  - name: place nginx.conf
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify: restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
tips:
  - "Use handlers for expensive actions"
  - "Multiple tasks can notify the same handler"
