title: "Playbooks & Roles"
playbook_anatomy: |
  ---
  - name: Configure web
    hosts: web
    become: true
    vars:
      web_pkg: "{{ 'httpd' if ansible_facts['os_family']=='RedHat' else 'apache2' }}"
    tasks:
      - package: { name: "{{ web_pkg }}", state: present }
      - service: { name: "{{ web_pkg }}", state: started, enabled: true }
role_layout: |
  roles/
    web/
      tasks/main.yml
      handlers/main.yml
      templates/index.html.j2
      defaults/main.yml
      vars/main.yml
      meta/main.yml
guidance:
  - "Put overridable vars in defaults/"
  - "Keep tasks small and composable"
